### ISSUE TITLE
[BUG]Unable to change player name color using luckperms

### ISSUE THREAD

**Issue by TinyMandalorian** [Ale32bit/Solstice#7]
Im unable to change the color of the players name in tab and in chat when trying to set the player's prefix 

/lp group default meta addprefix 1 "<#ADADAD>ᴛ<#ADADAD>ʀ<#ADADAD>ᴀ<#ADADAD>ɪ<#ADADAD>ɴ<#ADADAD>ᴇ<#ADADAD>ʀ <#ADADAD>"

Ive tried this and this doesnt work it used to work before the 1.0.0 update my config for chat right at the moment is 

  "module.styling.chatFormat": "%luckperms:prefix%%player:name%%luckperms:suffix%<dark_gray> » <white>${message}",

}
customName {
    # Customize player display names based on their LuckPerms group.
    name-formats=[
        {
            format="%player:name%"
            group=default
        }
    ]
}
![image](https://github.com/user-attachments/assets/e0d112f7-81c5-440c-8d44-3bef70ca4091)

**Comment by Ale32bit** [comment]
That would have been an unintended effect, `name-formats` should be used to colour and format the player display name.

**Comment by Ale32bit** [comment]
Supposing the colour of the name you want is `#ADADAD`, use:

- LuckPerms prefix: `"<c:#ADADAD>ᴛʀᴀɪɴᴇʀ</c> "`
- Default group name format: `"<c:#ADADAD>${name}</c>"`
- Chat format: `"%luckperms:prefix%%player:displayname%%luckperms:suffix%<dark_gray> » </dark_gray>${message}"`

**Comment by TinyMandalorian** [comment]
![image](https://github.com/user-attachments/assets/9cb30356-16a3-40c2-ae31-4d988209fccb)
![image](https://github.com/user-attachments/assets/a1116549-8d67-4069-a5db-d2935d287e72)

why doesnt this work then

**Comment by Ale32bit** [comment]
Move the owner config above default config

**Comment by TinyMandalorian** [comment]
![image](https://github.com/user-attachments/assets/9fb58585-d6ae-4ec8-9521-f80515629416)
![image](https://github.com/user-attachments/assets/f5acdaaa-3c4c-4d15-b476-b9af5a7ed118)

am i still doing something wrong?

**Comment by Ale32bit** [comment]
Looks good to me? What is the result that you want?

**Comment by TinyMandalorian** [comment]
well i removed my owner group so my name should've been gray.... not red

**Comment by Ale32bit** [comment]
Must be the cache, run `/solstice reload` to clear it

**Comment by TinyMandalorian** [comment]
didnt work

**Comment by Ale32bit** [comment]
Can you provide the config file + locale?

**Comment by TinyMandalorian** [comment]
[locale.json](https://github.com/user-attachments/files/18138062/locale.json)
[config.txt](https://github.com/user-attachments/files/18138064/config.txt)
I just renamed the config file to a txt file

**Comment by Ale32bit** [comment]
I cannot replicate the problem, username becomes gray after clearing the parent group from my user (and clearing cache too).

**Comment by TinyMandalorian** [comment]
weird

**Comment by Ale32bit** [comment]
Do you have any other mod installed? Maybe there is something conflicting with Solstice

**Comment by TinyMandalorian** [comment]
AchievementOptimizer-fabric-1.21.1-1.2.0.jar
alternate-current-mc1.21-1.9.0.jar
c2me-fabric-mc1.21.1-0.3.0+alpha.0.299.jar
cliff-face-2.0+1.21.jar
cloth-config-15.0.140-fabric.jar
fabric-api-0.110.0+1.21.1.jar
fabric-language-kotlin-1.13.0+kotlin.2.1.0.jar
fasterrandom-5.1.0.jar
ferritecore-7.0.2-hotfix-fabric.jar
flan-1.21.1-1.10.8-fabric.jar
ForgeConfigAPIPort-v21.1.2-1.21.1-Fabric.jar
getittogetherdrops-fabric-1.21-1.3.1.jar
lithium-fabric-0.14.3-snapshot+mc1.21.1-build.92.jar
LuckPerms-Fabric-5.4.140.jar
LuckPerms-Fabric-PlaceholderAPI-Hook.jar
Necronomicon-Fabric-1.6.0+1.21.jar
noisium-fabric-2.3.0+mc1.21-1.21.1.jar
placeholder-api-2.4.1+1.21.jar
RecipeCooldown-1.0.0.jar
ScalableLux-0.1.0+fabric.26c6e72-all.jar
servercore-fabric-1.5.5+1.21.1.jar
SkiesGUIs-fabric-1.21.1-1.6.0-BETA3.jar
solstice-1.1.0+1.21.1.jar
styled-sidebars-1.5.0+1.21.jar
tectonic-fabric-1.21.1-2.4.1a.jar
Terralith_1.21.x_v2.5.7.jar
threadtweak-fabric-0.1.5+mc1.21.1.jar
vanish-1.5.9+1.21.1.jar
worldedit-mod-7.3.8.jar
yawp-0.0.2.10-alpha2.jar

**Comment by Ale32bit** [comment]
See if it works correctly alone with no other mods (except Fabric API, LuckPerms and LP Placeholder API).
If it does I suggest you do a binary search of the mods, that is:

> A binary search can be used to quickly find a specific mod causing trouble, which can be especially useful when logs don't give a conclusive answer to your issue.
> 
>Start by removing or disabling half of your mods, then test if the problem still occurs. If it does, remove half of the remaining mods and test again. If it doesn't, add back half of the mods you just removed.
> 
>Keep in mind you don't have to stick strictly to halves each time, and may have to enable some library mods like Fabric API out of order.
> 
> By repeating this on an increasingly smaller set of mods, you'll find the problematic mod within a few iterations.

**Comment by TinyMandalorian** [comment]
[14:00:58] [main/INFO]: Compatibility level set to JAVA_21
[14:00:58] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[14:01:07] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'solstice' at 'me.alexdevs.solstice.Solstice'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.9.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: com/typesafe/config/ConfigException
        at knot/me.alexdevs.solstice.util.data.HoconDataManager.getLoader(HoconDataManager.java:37) ~[solstice-1.1.0+1.21.1.jar:?]
        at knot/me.alexdevs.solstice.util.data.HoconDataManager.setDataPath(HoconDataManager.java:54) ~[solstice-1.1.0+1.21.1.jar:?]
        at knot/me.alexdevs.solstice.util.data.HoconDataManager.<init>(HoconDataManager.java:32) ~[solstice-1.1.0+1.21.1.jar:?]
        at knot/me.alexdevs.solstice.Solstice.<clinit>(Solstice.java:38) ~[solstice-1.1.0+1.21.1.jar:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: com.typesafe.config.ConfigException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at knot/me.alexdevs.solstice.util.data.HoconDataManager.getLoader(HoconDataManager.java:37) ~[solstice-1.1.0+1.21.1.jar:?]
        at knot/me.alexdevs.solstice.util.data.HoconDataManager.setDataPath(HoconDataManager.java:54) ~[solstice-1.1.0+1.21.1.jar:?]
        at knot/me.alexdevs.solstice.util.data.HoconDataManager.<init>(HoconDataManager.java:32) ~[solstice-1.1.0+1.21.1.jar:?]
        at knot/me.alexdevs.solstice.Solstice.<clinit>(Solstice.java:38) ~[solstice-1.1.0+1.21.1.jar:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 7 more


I got no idea whats happening now i just removed all other mods besides the required ones...

**Comment by Ale32bit** [comment]
Update to 1.1.1

**Comment by TinyMandalorian** [comment]
it kinda works for some reason i have to relog or reload the config in order to see the updated name color

**Comment by Ale32bit** [comment]
That is normal, it's the only way I could make custom nicknames work.

**Comment by TinyMandalorian** [comment]
is there a way I can disable solstice chat function and use styled chat? or will it just work fine

**Comment by Ale32bit** [comment]
I'll look into adding it

**Comment by TinyMandalorian** [comment]
thanks

**Comment by TinyMandalorian** [comment]
it looks like you would have to try and disable the mixions for changing join messages advancements death messages and chat format to get it to work i tried them both together and it just threw a bunch of errors and didnt start

**Comment by Ale32bit** [comment]
This is much more work than expected, I am not be able to implement this at the moment without changing how config is loaded

**Comment by Ale32bit** [comment]
Just released an update that adds `${prefix}` and `${suffix}` placeholders to name formats, these are added before being processed as formatted text, so opening a tag (eg. `<gray>`) will have effects to the rest of the string (eg. `${prefix}${name}${suffix}`).

If the prefix is `<gray>my prefix ` then the result would be `<gray>my prefix MyName` and all text will be gray when formatted.

**Comment by TinyMandalorian** [comment]
Thank you so much this fixed all my issues
